### ISSUE TITLE
Need to update ThaliBuildBot and ThaliTest to 2FA

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#100]
On 1/17 Microsoft policy is going to remove all members of the Thali project that do not have 2FA enabled. This has been in the works for some time and I've mentioned it before but we put it off because we had other things to worry about. Well, now we can't put it off anymore because neither the ThaliBuildBot or ThaliTest have 2FA. 

In the case of the ThaliBuildBot I'm not sure how much this matters. If we just turn on 2FA everything might continue to work fine because I believe the ThaliBuildBot is used to receive web hook events. So Github is contacting the ThaliBuildBot, not the other way around. I think. The bigger problem is, who has the credentials for the ThaliBuildBot?!?! Without those credentials we can't even turn 2FA on!

In the case of the ThaliTest bot we have both the problem of finding the password that lets us log in and and set it to 2FA. Then we have the problem that ThaliTest is calling the GitHub APIs and so really does need to use 2FA properly. The actual fix is pretty simple. We just need to go to https://github.com/settings/tokens when logged in as ThaliTest and generate a token. This token is then used as the password in basic auth.

So the work items here are:
1. Figure out who has the passwords for ThaliBuildBot and ThaliTest
2. Set both ThaliBuildBot and ThaliTest to be 2FA
3. Generate the personal access token for ThaliTest (I don't think we need it for ThaliBuildBot, could be wrong) and configure CI to use it when doing basic auth to the GitHub API.

**Comment by lesn1kk** [comment]
I enabled 2FA on ThaliTester profile and set personal token in CI. I don't know what is purpose of ThaliBuildBot and don't even know credentials for this account so I will leave it for now.
