### ISSUE TITLE
CI might sometimes run old/other apps concurrently with the app under testing

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/CI#11]
For example at:
https://github.com/ThaliTester/TestResults/blob/49526184a3a5cb3_Reproduce_network_reliability_issues_in_the_CI__vjrantal/test_log.md

We can see that logcat output contains output from the app that is under test, but also from another app (different package id).

Old apps that were tested in the CI should be properly shut down and cleaned up so that they don't interfere with new test runs.

**Comment by obastemur** [comment]
After every test, the android devices will be rebooted.

**Comment by vjrantal** [comment]
@obastemur: Can you also confirm that you fix the cleanup part so that an old app from previous CI runs will be uninstalled?

This isn't what our current app does, but an old app (or a service) could get started on device boot (if it is defined that way).

**Comment by obastemur** [comment]
It's already part of the fix (preboot)
