### ISSUE TITLE
More verbose output format with logcat in CI

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/CI#12]
To get more information via logcat, we could pass `-v threadtime` to logcat.

There would also be `-v long`, but based on current understanding, that wouldn't bring useful new information and would generate longer outputs.

Output formats documented at http://developer.android.com/tools/debugging/debugging-log.html#outputFormat.

**Comment by obastemur** [comment]
I would rather prefer you / @yaronyg to pick the format instead of finding out the right one. FYI; threadtime doesn't have package name. Please make sure the format is playing nicely with the filtering efforts.

**Comment by vjrantal** [comment]
@obastemur: If I am not mistaken, none of the formats have package name. Please correct me if I am mistaken.

Your suggestion is good - I'll check with @yaronyg first what we should do with this one.

**Comment by obastemur** [comment]
FYI, applying filter breaks the format. We do apply a filter to grab the app specific logs.

**Comment by vjrantal** [comment]
`-v threadtime` did not work on all devices so it was decided that it is not taken into use.
