### ISSUE TITLE
CI doesn't seem to test the merged content with PRs

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/CI#13]
When doing a PR, an important aspect to verify is how the new code works together with the base branch it targets. Here is a quote from [Travis docs](http://docs.travis-ci.com/user/pull-requests/) how they explain is:

```
Rather than test the commits from the branches the pull request is sent from, we test the merge between the origin and the upstream branch.
```

Currently, it seems like the CI system tests the code from the branch the pull request is from and not the merged content.

@yaronyg: Can you confirm how we would like this to work?

@obastemur: Please correct me if I had misunderstood the current CI behavior.

**Comment by obastemur** [comment]
CI works as it is designed. Current behavior is to test PR as whole and trigger the test again and again with each commit.

**Comment by obastemur** [comment]
Gonna `rebase` from master

**Comment by yaronyg** [comment]
This should be enabled in a couple of hours.

**Comment by obastemur** [comment]
Done. @vjrantal thanks for the details.
