### ISSUE TITLE
CI sometimes posts wrong log files

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/CI#17]
I run a test at https://github.com/thaliproject/Thali_CordovaPlugin/pull/340#issuecomment-157717580 but when I followed the results link, some devices seems to have log results from some previous runs.

For example, open https://github.com/ThaliTester/TestResults/blob/51074821f72e61a_Enable_native_layer_and_replication_tests__vjrantal/thali07_samsung-SM-A500FU.md and search for string:

`execPath /data/data/com.example.hello/files/www/jxcore`

The reason why this line is suspicious is that the package name of the app under this test is not `com.example.hello` but should be `com.test.thalitest`.

**Comment by obastemur** [comment]
perhaps '-c' call failed and device restart didn't cleanup the log.. I may skip the first batch of log though ?

**Comment by vjrantal** [comment]
> perhaps '-c' call failed and device restart didn't cleanup the log

@obastemur: I suspect that is not the only issue, because searching `com.test.thalitest` from the log doesn't give any results so it almost looks like the test app wasn't ever run during the time when the posted log was gathered.

**Comment by vjrantal** [comment]
This issue was fixed and currently the posted logs match to the test run.
