### ISSUE TITLE
CI doesn't build per commit, but per branch.

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/CI#20]
If I have a PR from a branch to which I push two commits fairly close to each other, CI is triggered twice (which is expected), but ends up building using the most recent commit, because it does the checkout based on the branch and not based on the commit sha1.

This might be seen as an unexpected behavior when afterwards looking at the logs since the logs are posted as if the test run was made using a certain commit sha1, which isn't the one CI actually used.

**Comment by obastemur** [comment]
Fixed
