### ISSUE TITLE
Upgrade to latest adb

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/CI#28]
For marshmallow, we would need adb that supports the -g switch to grant all runtime permissions.

**Comment by vjrantal** [comment]
@obastemur: Did you build yourself the current arm binaries of adb or did you download them from somewhere?

**Comment by obastemur** [comment]
I had patched and compiled since no official ARM adb support.

**Comment by vjrantal** [comment]
Seems that we don't need this after all, because the permissions can be granted also after installation with something like `adb shell pm grant`.
