### ISSUE TITLE
Review adb commands for failure cases

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/CI#29]
In `android.js` there are several places where adb command is issued and it is considered an error case only if the exit code of adb is non-zero. However, that is often not the case, for example:

```
$ adb -s VS986da9f36ea install ~/Desktop/android_0_625481247756efd.apk 
2953 KB/s (47606904 bytes in 15.741s)
    pkg: /data/local/tmp/android_0_625481247756efd.apk
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]
$ echo $?
0
```

In above, adb install fails, because the signature in the .apk is different than what is installed on the device. This is as expected, but the as seen above, the exit code is 0.

The failure conditions probably require additional checks to ensure commands worked as expected. For example, when installing an app, it might be required to issue something like `shell pm list packages | grep <package-name>` and make sure the app actually got installed to the device and fail if not.

**Comment by vjrantal** [comment]
I temporarily included more debugging of the adb install command by printing the stdout to the log that gets posted. That can be seen at https://github.com/ThaliTester/TestResults/blob/62548124ece3ba0_More_thaliMobileNativeWrapper_vjrantal/test_log.md.

One of the devices showed `Error: Could not access the Package Manager.  Is the system running?` and two had `- waiting for device -`.

My proposal to fix the installation issue would be that after the adb install command, there is a check with `adb shell pm list packages` that the app package that we are installing is found from the list. If not, a retry for the adb install is scheduled. Maybe do 3 retries or so and after that, give up on that device.

**Comment by vjrantal** [comment]
Furthermore, the current CI code has in `android.js` something like this:

```
// remove apps
for (var i = 0; i < arrDevices.length; i++) {
  stopAndroidApp(job.config.csname.android, arrDevices[i].deviceId);
  uninstallApp(job.config.csname.android, arrDevices[i].deviceId);
}

var retry_count=0;
// deploy apps
for (var i = 0; i < arrDevices.length; i++) {
  var res = deployAndroid(builds + "/android_" + nodeId + "_" + job.uqID + ".apk", arrDevices[i].deviceId);
```

In the `stopAndroidApp` there is an adb reboot command issued. It could be investigated if sometimes the device is still rebooting itself when the adb install commands are tried out that causes failures.

**Comment by czyzm** [comment]
The reboot may be an issue as well. We can check if all devices are booted before issuing installation by pulling sys.boot_completed property.

**Comment by vjrantal** [comment]
Do you mean currently the reboot might not happen on all devices? I have seen that happening as well.

The way I have checked is `adb shell uptime` and noticed that sometimes devices have been up longer than expected.

**Comment by czyzm** [comment]
What I meant is that app may fail to install because the install is issued while device is rebooting. I don't know if this is possible that reboot will not happen.

**Comment by vjrantal** [comment]
The "reboot didn't happen" might related to the offline/unauthorized issue that you fixed earlier. That is, we tried to do the reboot operation to devices that adb can't control and that is why it didn't work.
