### ISSUE TITLE
Have Marshmallow devices in the device pool

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/CI#30]
For Marshmallow devices to work, the CI code needs to be updated to issue a command like:

`adb shell pm grant <package name> android.permission.ACCESS_COARSE_LOCATION`

after the app is installed.

Proposal is that since node thali09 is currently used for offline testing, that node would also be used to test this code change and eventually have 2 Marshmallow devices plugged into it and then the node could be enabled back in CI configuration.

**Comment by vjrantal** [comment]
@czyzm: After you have an environment where you can iterate on the CI code related to dealing with Android devices, you could also start thinking how this could be implemented. There was the one Nexus that already got upgraded to Marshmallow and if I remember right, there was another Nexus that is currently taken away that could be upgraded as well once this starts working.

**Comment by yaronyg** [comment]
This is a bug because until we fix it we can't test Marshmallow devices in CI and we need to do that.
