### ISSUE TITLE
Build failures sometimes result in no logs

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#39]
Check out https://github.com/thaliproject/Thali_CordovaPlugin/pull/724#issuecomment-218925065 for example. I did get output from Appveyor but the logs for CI are empty. This makes debugging a nightmare.

**Comment by vjrantal** [comment]
The missing logs looks similar as https://github.com/thaliproject/CI/issues/24.

Can it be that there is something in the commit-under-test that makes the test process get stuck or not start at all?

From the logs of the latest build at https://ci.appveyor.com/project/thaliproject/thali-cordovaplugin/build/1.0.495 it seems like the test files load, but the coordinated test run doesn't start.

**Comment by yaronyg** [comment]
It seems weird that it wouldn't run at all. I wondered if maybe the d/ls were so damn slow that it took an hour to start the tests? Right now it all works on my desktop and until the new folks show up that will have to do. :(
