### ISSUE TITLE
CI appears to be running an old version of JXcore

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#43]
When our tests run in CI I am getting the error:

Missing PFX or certificate + private key.

I believe this error is from an old version of Shawn's build of JXcore before he fixed the need to put in a PFX cert even when you were using PSK. So we need to update the version of JXcore in CI to the latest so we don't see this error.

**Comment by jareksl** [comment]
The jxcore on the CI server is now upgraded to the latest (v. 3.1.2). The jxcore on the VM was already up to date.
