### ISSUE TITLE
Document what we need to install in the CI VM

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#46]
We have never written down what software needs to be on the CI VM to work so if we lose the VM We are in a bad place.

**Comment by yaronyg** [comment]
Please make sure to add the Sinopia set up once I check that in.

**Comment by yaronyg** [comment]
Should be finished today or tomorrow.

**Comment by larryonoff** [comment]
We've integrated swfitlint into Xcode build steps, so this tool is needed for macOS environment. See swiftlint [installation guide](https://github.com/realm/SwiftLint#installation). I recommend to install it using Homebrew.

**Comment by larryonoff** [comment]
I also prefer having CocoaPods (but not from root, so it looks that we need rvm or rbenv) and Carthage installed on CI (these are Xcode package managers). There're not used yet, but it definitely can be.
