### ISSUE TITLE
tests are not giving results

### ISSUE THREAD

**Issue by DrJukka** [thaliproject/CI#5]
in: https://github.com/thaliproject/Thali_CordovaPlugin/pull/223#issuecomment-152262759

There is successful build with 20 minutes timeout that has not been completed for 4 hours.

And second one which has been build hour ago. 

Suspecting something being wrong with CI

**Comment by obastemur** [comment]
[See notes on slack]

Emptied the CI queue. Looks like the one with deleted branch was blocking everything else.
