### ISSUE TITLE
Make sure CI's router isn't allowing the iOS devices to talk to each other over the local WiFi

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#60]
We have a new router in CI and we need to make sure that it is configured so that the iOS devices can get to the coordination server (which btw has an Internet routable address) but can't get to any of the other iOS devices over the local wifi or this will invalidate our MPCF testing as we will be testing over normal wifi and not using the P2P radio features.

Please also update the CI README to point out the need for this and explain how we did it with what ever router we are currently using.

**Comment by jareksl** [comment]
All IOS devices are connected to Guest Access Point which disallow to connect to the local network.
