### ISSUE TITLE
We need to upgrade the CI host machine and VM to using El Capitan and to having the latest XCode

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#61]

**Comment by yaronyg** [comment]
The VM is upgraded but the host isn't yet because we didn't want to do that during the day because then nobody could work. So he will do it during the long weekend.

When we run the build from vNext everything goes fine, applications are build and deployed. But when we use Ilya's branch we still have the problem that made us do the upgrade in the first place.

**Comment by jareksl** [comment]
The host machine is upgraded to EL Capitan. The Xcode needs to be upgraded (waiting for IT to assign an account with apple developer program)

**Comment by yaronyg** [comment]
We are still blocked waiting for a response from IT

**Comment by jareksl** [comment]
The latest version of the Xcode (7.3.1) and its all required components are installed.
