### ISSUE TITLE
Please move the iOS devices to the non-guest network in CI

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/CI#63]
Until we have the native layers back we are going to test using the wifi based mock. So we need to move all the iOS devices over to the non-guest network in CI so that the wifi based mock will work.

**Comment by czyzm** [comment]
iOS devices moved to non-guest network.

**Comment by yaronyg** [comment]
@artemjackson With this fix you should be able to submit https://github.com/thaliproject/Thali_CordovaPlugin/issues/914 plus https://github.com/thaliproject/Thali_CordovaPlugin/issues/915 (I would join them into a single PR) to CI And have them pass on both Android and iOS.
