### ISSUE TITLE
CI communication between devices and coordination server is broken

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/CI#67]
We can see that devices trie to connect to coordination server and they can't connect.

Please see the log example (this log won't provide you with a lot info, because logs contains less info that needed). https://raw.githubusercontent.com/ThaliTester/TestResults/8291203064a8f9d__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/thali01_motorola-Nexus%206.md

**Comment by larryonoff** [comment]
@artemjackson will provide more detailed logs.

**Comment by artemjackson** [comment]
From this [log](https://raw.githubusercontent.com/ThaliTester/TestResults/8461863721be5f3_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/thali04_HTC-HTC%20One%20M9.md) we can see(search for `ThaliTape`)  that device tried to connect to th CoordinationServer but got no success.

**Comment by yaronyg** [comment]
@czyzm mentioned that some devices are connecting but not all and the tests fail if all don't correct.

**Comment by yaronyg** [comment]
We will wait on this one until we have the CI smoke test properly working.

**Comment by yaronyg** [comment]
Artem's tests showed that we are able to communicate via WiFi so the failures we are seeing are probably our own fault.
