### ISSUE TITLE
ERROR thaliPeerPoolDefault: Got error: 'Error: Could not establish TCP connection'

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/CI#75]
I've found a bug in `vNext_aaladev_417_812_1034`: `jx runCoordinatedTests.js` will be finished successfully, but we can see an exception `ERROR thaliPeerPoolDefault: Got error: 'Error: Could not establish TCP connection'` after all tests finished.

It looks like some test didn't clear its resources after teardown. We need to investigate it.

**Comment by yaronyg** [comment]
We haven't found the exact problem. There is an issue in thaliNotificationAction. It looks like we aren't cleaning all resources properly.

**Comment by yaronyg** [comment]
This was filed in the wrong repo. Closing in favor of thaliproject/Thali_CordovaPlugin#1078
