### ISSUE TITLE
Make CI able to run smoke tests if we want

### ISSUE THREAD

**Issue by lesn1kk** [thaliproject/CI#79]
We need to implement some logic when CI will enter test mode. Probably by adding additional field in mobile_test.json, then when someone will want to run smoke tests, he will have to enable it like:
"test": "true" or something.

**Comment by yaronyg** [comment]
@mlesnic I removed the assignees because this isn't currently scheduled.

**Comment by yaronyg** [comment]
This is implemented in thaliproject/Thali_CordovaPlugin#1030 and is a dupe of thaliproject/CI#74
