### ISSUE TITLE
Android logcat logs not available from all devices

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/CI#9]
As an example, see https://raw.githubusercontent.com/ThaliTester/TestResults/486007970c43223_Story_001_juksilve_DrJukka/test_log.md where there is 21 Android devices participating to the test.

On app startup, this line is printed to the jxcore log:
`Initializing JXcore engine`

Above line is found from the linked test results page 13 times, which indicates the the logcat output was available for 13/21 devices.

As a side note, the coordination server indicates that at least 19 devices were able to connect to it so at least 19 devices have been able to successfully start the app and thus at least 19 logcat outputs should be available.

**Comment by obastemur** [comment]
@vjrantal is this still an issue ?

**Comment by vjrantal** [comment]
I haven't yet been able to verify, but if this should be fixed, I think it makes sense to close.

Let's just re-open if we see this in the future.

**Comment by vjrantal** [comment]
Based on my testing today, the logcat output is now available from all devices. Thanks a lot!
