### ISSUE TITLE
Remove 20 min timeout for one operation

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/CI#90]
We have timeout in https://github.com/thaliproject/CI/blob/master/builder/virtual.js

var eopts = {
  encoding: 'utf8',
  timeout: 1200000, // single command timeout - 20 min.
  maxBuffer: 1e9,
  killSignal: 'SIGTERM'
};

I have a bunch of PRs failed because of that
https://github.com/thaliproject/Thali_CordovaPlugin/pull/1576
https://github.com/thaliproject/Thali_CordovaPlugin/pull/1568

**Comment by larryonoff** [comment]
done
